# Generated by Django 3.2.9 on 2021-12-02 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211202_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='body',
            new_name='name',
        ),
    ]
